### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by loranger** [RahulDey12/laravel-console-spinner#3]
Hello,

Thank you for this awesome customizable spinner !
I'd like to use it in order to wait for a sub-process to finish.
I can't have any progress, and I'd like to use this spinner to spin indefinitely until I stop it.

Is it possible to achieve something like this ?

```php
$spinner = $this->spinner();
$spinner->setMessage('Loading...');
$spinner->start();

Terminal::run("sleep 120");
$spinner->stop();
```

**Comment by RahulDey12** [comment]
@loranger I will look at it but initially, you could use React PHP event loop or something.
